[package]
name = "graphicgene-wasm"
version.workspace = true
edition.workspace = true
license.workspace = true
description = "wasm-bindgen bindings for graphicgene"

[lib]
crate-type = ["cdylib", "rlib"]

[dependencies]
graphicgene-core.workspace = true
graphicgene-render.workspace = true
kurbo.workspace = true
serde.workspace = true
serde_json.workspace = true
slotmap.workspace = true
tiny-skia = "0.12"
wasm-bindgen = "0.2"
